apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-priv
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-priv
  template:
    metadata:
      labels:
        app: go-priv
    spec:
      containers:
      - name: go-priv
        image: ejosephodom/go-priv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
